<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<link rel="icon" type="image/png" href="/assets/images/favicon.png" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TOS</title>
<!-- adding bootstrap.css and the needed styling -->
<link href="{{ asset('chargebee') }}/assets/css/bootstrap.min.css" rel="stylesheet">
<link href="{{ asset('chargebee') }}/assets/css/style.css" rel="stylesheet">
<!-- adding HTML5.js -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js"></script>
</head>
<body>
<div class="navbar-static-top">
<div class="container">
<div class="h2">Terms of Service</div>
</div>
</div>
<div class="jumbotron text-center">
    <div class="container">
    	<div class="l_main">1. Overview. Prepreso recognizes and respects your privacy. The following Privacy Policy tells you about the information that Prepreso collects through the Service, how we use that information and how you can opt out of certain uses of information we may collect. This Privacy Policy, along with the General Terms and Conditions, the Content Policy, and the Copyright Policy, forms an integral part of the Agreement. If you do not agree with all of the terms and provisions of this Privacy Policy, you may not use the Service. If you access the Service you are consenting to the information collection and use practices described in this Privacy Policy, as revised from time to time by us.</div>
    <div class="l_main">2. Privacy Standards. Prepreso adheres to the U.S. Safe Harbor privacy principles of Notice, Choice, Onward Transfer, Security, Data Integrity, Access and Enforcement.</div>	
    <div class="l_main">3. Information Site Capture May Collect About You. We collect the following general types of information from users of the Service.</div>	
    <div class="s_main">3.1. "Personal Information" is information used by Prepreso to identify you individually, such as your name, email address and address.</div>
    <div class="s_main">3.2. "Aggregate Information" is information that does not contain Personal Information or from which Personal Information has been removed. Aggregate Information is information about use of the Service, such as the number of users of the Service and their location.</div>
    <div class="s_main">3.3. The actual information we collect from you depends in part on how you use the Service. The following is a more detailed explanation of some of the types and uses of information we collect</div>
    <div class="m_main">3.3.1. Registration Information. Prepreso requests certain Personal Information when you sign up to for the Service, including your email address and a password. Your email address is used to communicate with you. Your password is used to protect your account from unauthorized access. The information requested may depend on your desired use of the Service.</div>
    <div class="m_main">3.3.2. Information in your Content. Content that you create, publish or store through the Service may include Personal Information about you. You are solely responsible for the Content you create, publish and store, and the Personal Information it may contain. We advise you use caution in publishing Content containing Personal Information.</div>
    <div class="m_main">3.3.3. Additional Profile Information Provided by You. In addition to allowing you to create, publish and store Content, the Service allows you to provide additional profile information, such as a user name, photo, birthday, location in connection with Content you publish. You should also use caution in publishing or making such additional profile information publicly available.</div>
    <div class="m_main">3.3.4. Use Information. Prepreso automatically records information about your use of the Service, such as when and how you use the Service, including the frequency and size of data transfers. Information displayed or clicked in using Service interfaces (including UI elements, settings, and other information) may also be recorded.</div>
    <div class="m_main">3.3.5. Email Services. If you provide us with your email address and opt-in to any email notification features that Prepreso may now have or may develop in the future, you may receive email from time to time from Prepreso. Each email of this nature that you receive from Prepreso will contain an "unsubscribe" link at the bottom of the email message which will provide you the opportunity to opt-out of receiving future communications from Prepreso by clicking on the "unsubscribe" link and following the unsubscribe instructions.</div>
    <div class="m_main">3.3.6. Administrative Purposes. We may collect and use information that identifies you personally when you submit comments, questions or suggestions about or through the Service. For example, if you submit questions to us or information requests, we will use the information you provide to respond to you. We also may collect and use your information to contact you when necessary for other administrative purposes. If you submit comments, questions or suggestions, do not include confidential personal or financial information in such requests. Such email will be maintained in accordance with our corporate email and document retention policies.</div>
    <div class="l_main">4. Disclosure of Your Personal and Aggregate Information.</div>
    <div class="s_main">4.1. Personal Information. Prepreso will not sell or disclose your Personal Information to third parties without your consent except as set forth herein.</div>
    <div class="m_main">4.1.1. Your Content and Presentations. Prepreso may, but is under no obligation to, monitor, screen or edit Content created, published or stored by users of the Service. You are solely responsible for Personal Information that becomes available to the public or other users that you have elected to publish or otherwise make available to third parties through the Service, including without limitation on myPrepreso.com</div>
    <div class="m_main">4.1.2. Consultants. From time to time Prepreso engages consultants that may need access to the information we collect to perform their services for us. We require that our consultants keep Personal Information confidential and use it only in accordance with the service agreement between Prepreso and such consultant.</div>
    <div class="m_main">4.1.3. Legal Requirements. We may disclose your Personal Information if required to do so by law or if we believe that such action is reasonably necessary to: (a) conform with the law, respond to claims or comply with legal process served on Prepreso; or (b) protect and defend our rights or property, including the Service, our employees, guests or the public.</div>
    <div class="m_main">4.1.4. Company Sale. Because information collected through the Service may constitute a trade secret and asset of Prepreso, we may disclose or sell such information in the event we entertain the sale of Prepreso or some or all of its assets.</div>
    <div class="m_main">4.1.5. Aggregate Information: Prepreso collects Aggregate Information about you and your use of the Service whenever you use the Service. Prepreso may collect, compile, store, publish, promote, report, sell, or otherwise disclose or use any and all Aggregate Information, provided that it does not result in disclosure of any Personal Information that identifies or can be readily correlated to you.</div>
    <div class="l_main">5. Cookies. Prepreso may make use of "cookies" in connection with the Service. However, you may block or remove cookies at your discretion at any time. Cookies are small text files that are stored on a user's computer by a web server based on the permissions set in a user's browser software to identify the user's computer to a service provider that may correlate other information, including personal information, with the cookie. Cookies allow Prepreso to automate access and data entry functions of the Service such as login information, tailor the Service to your preferences or interests, or customize promotions or marketing. In addition, cookies allow us to track usage of the Service to determine which parts of the Service are useful or popular and which are not, thereby enabling us to improve and update the Service effectively.</div>
    <div class="l_main">6. Security. Prepreso uses reasonable efforts to store and maintain Personal Information to protect it from loss, misuse, alteration or destruction by any unauthorized party. We store no social security information of users. We make reasonable efforts to attempt to prevent the unauthorized access of our systems containing Personal Information.</div>
    <div class="l_main">7. Breach of Security. In the event of a breach of our information system security that may compromise your Personal Information, we will promptly notify you of such breach at the e-mail address that we have on file for you. We reserve the right to reasonably delay such notification as may reasonably be necessary as part of any internal investigation or law enforcement efforts related to such breach. To respect the privacy of children and to comply with the Children's Online Privacy and Protection Act, we do not collect Personal Information from children under the age of 13. Children under the age of 13 are prohibited from using the Service.</div>
    <div class="l_main">8. Outside Links. In connection with the Service, Prepreso may refer or provide you a link to third-party websites. A link to such a third party service does not imply endorsement of that site nor any ability to control that site's privacy practices. Be aware that third party services may collect data and personal information and operate according to their own privacy practices. Therefore, you should carefully review the privacy policies of third party services before submitting any Personal Information to them.</div>
    <div class="l_main">9. Opting Out; Removal of Personal Information and Contacting Us. Any time your provide us with Personal Information, we will provide you with the opportunity to opt out of receiving further communications from us, although this may limit or eliminate your access to the Service. To opt out of receiving further communications or to unsubscribe from any specific aspect of the Service, please email a request to support@myPrepreso.com. If you have questions or concerns about this Policy, or the accuracy of any Personal Information we hold about you, please contact us at support@myPrepreso.com. You may request removal of your Personal Information from our system(s) by contacting support@myPrepreso.com. We will comply with your request to the extent we are required to maintain your information in accordance with our document retention policies or applicable laws or regulations. If at any time you feel that Prepreso has not adhered to this policy, please email us at support@myPrepreso.com. We will respond promptly to your concerns.</div>  
    </div>
</div>
</body>
</html>